baseURL = "https://dev.s11.no/"
languageCode = "en-GB"
title = "s11.no ≔ з11.ею"
theme = "ronu"
siteDescription = "Scalable, Sustainable, Supported, Standard, open-Source Software and Service Solutions from Stavanger to Stockport"
mainSections = ["post"]

[[menu.main]]
        name = "Blog"
        url = "/posts/"

[[menu.main]]
        name = "About"
        url = "https://www.research.manchester.ac.uk/portal/soiland-reyes.html"

[[menu.main]]
        name = "Publications"
        url = "https://orcid.org/0000-0001-9842-9718"


[params]
        authorName = "Stian Soiland-Reyes"
        twitterURL = "https://twitter.com/soilandreyes"
        linkedinURL = "https://uk.linkedin.com/in/stain"
        githubURL = "https://github.com/stain/"
        #email = "stian@soiland-reyes.com"
        orcidURL = "https://orcid.org/0000-0001-9842-9718"

