#baseURL: "./"
languageCode:: "en-GB"
title: "s11.no ≔ з11.ею"
theme: "ronu"
siteDescription:: "Scalable, Sustainable, Supported, Standard, open-Source Software and Service Solutions from Stavanger to Stockport"
# mainSections: ["post"]
relativeURLs: true

#[[menu.main]]:
#  name: "Blog"
#  url: "/posts/"

menu:
  main:
    - name: "About"
      url: "/2021/about/"
    - name: "Publications"
      url: "2021/publications/"
    - name: "Archive"
      url: "/2021/archive/"
    - name: "House rules"
      url: "/2021/house-rules/"

params:
  authorName: "Stian Soiland-Reyes"
  twitterURL: "https://twitter.com/soilandreyes"
  linkedinURL: "https://uk.linkedin.com/in/stain"
  githubURL: "https://github.com/stain/"
  orcidURL: "https://orcid.org/0000-0001-9842-9718"
  YEAR: 2021   # Year used in permalinks
  htaccess: |
    RedirectMatch 301 ^/2020/archive/$ /2021/archive/
    Redirect 301 /2020/categories/ /2021/categories/
    Redirect 301 /2020/tags/ /2021/tags/
    


permalinks:
  /: /:year/:filename/
  posts: /:year/:filename/
  tags: /2021/tags/:slug/
  categories: /2021/categories/:slug/


taxonomies:
  category: categories
  tag: tags
  
#disableKinds:
#  - taxonomy
#  - term  


mediaTypes:
  "text/x-htaccess":
    suffixes: ["htaccess"]

outputs:
  home: ["HTML", "htaccess"]

outputFormats:
  htaccess:
    baseName: ""
    isPlainText: true
    mediaType: text/x-htaccess
