baseURL: "./"
languageCode:: "en-GB"
title: "s11.no ≔ з11.ею"
theme: "ronu"
siteDescription:: "Scalable, Sustainable, Supported, Standard, open-Source Software and Service Solutions from Stavanger to Stockport"
# mainSections: ["post"]
relativeURLs: true

#[[menu.main]]:
#  name: "Blog"
#  url: "/posts/"

menu:
  main:
    - name: "About"
      url: "https://www.research.manchester.ac.uk/portal/soiland-reyes.html"
    - name: "Thoughts"
      url: "2020/"
    - name: "Publications"
      url: "https://orcid.org/0000-0001-9842-9718"

params:
  authorName: "Stian Soiland-Reyes"
  twitterURL: "https://twitter.com/soilandreyes"
  linkedinURL: "https://uk.linkedin.com/in/stain"
  githubURL: "https://github.com/stain/"
  orcidURL: "https://orcid.org/0000-0001-9842-9718"
  YEAR: 2020   # Year used in permalinks 

permalinks:
  /: /:year/:filename/
  posts: /:year/:filename/
  tags: /2020/tags/:slug/
  categories: /2020/categories/:slug/


taxonomies:
  category: categories
  tag: tags
  
#disableKinds:
#  - taxonomy
#  - term  