#baseURL: "./"
languageCode:: "en-GB"
title: "s11.no ≔ з11.ею"
theme: "ronu"
siteDescription:: "Scalable, Sustainable, Supported, Standard, open-Source Software and Service Solutions from Stavanger to Stockport"
# mainSections: ["post"]
relativeURLs: true

#[[menu.main]]:
#  name: "Blog"
#  url: "/posts/"

menu:
  main:
    - name: "About"
      url: "/2022/about/"
    - name: "Publications"
      url: "2022/publications/"
    - name: "Archive"
      url: "/2022/archive/"
    - name: "House rules"
      url: "/2021/house-rules/"
    - name: "PhD"
      url: "/2022/phd/"

params:
  authorName: "Stian Soiland-Reyes"
  twitterURL: "https://twitter.com/soilandreyes"
  linkedinURL: "https://uk.linkedin.com/in/stain"
  githubURL: "https://github.com/stain/"
  orcidURL: "https://orcid.org/0000-0001-9842-9718"
  YEAR: 2022   # Year used in permalinks
  htaccess: |
    RedirectMatch 301 ^/202[01]/archive/$ /2022/archive/
    Redirect 301 /202[01]/categories/ /2022/categories/
    Redirect 301 /202[01]/tags/ /2022/tags/
    AddDefaultCharset UTF-8
    AddType text/plain .md5
    AddType text/plain .sha1
    Header set Access-Control-Allow-Origin "*"
    ErrorDocument 404 /404.html
    IndexOptions Charset=UTF-8
    IndexOptions -FancyIndexing -HTMLTable +FoldersFirst +NameWidth=40 +TrackModified
    <FilesMatch "\.html$">
      Header add Link "</css/bundle.css>;rel=preload"
      Header add Link "</images/cc-by-4.0.svg>;rel=preload"
    </FilesMatch>

permalinks:
  /: /:year/:filename/
  posts: /:year/:filename/
  tags: /2022/tags/:slug/
  categories: /2022/categories/:slug/


taxonomies:
  category: categories
  tag: tags
  
#disableKinds:
#  - taxonomy
#  - term  


mediaTypes:
  "text/x-htaccess":
    suffixes: ["htaccess"]

outputs:
  home: ["HTML", "htaccess"]

outputFormats:
  htaccess:
    baseName: ""
    isPlainText: true
    mediaType: text/x-htaccess

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
